@startuml
title Диаграмма прецедентов - Реестр организаций

rectangle "Реестр организаций" as regOrg {
    package "Прецеденты.Доступ: Введение" as CRUD_FUNC {
         usecase "Добавить организацию\n в реестр" as addOrg
        usecase "Удалить организацию\n из реестра" as deleteOrg
        usecase "Редактирование организации\n в реестре" as updateOrg
    }
    package "Прецеденты.Доступ: Просмотр" as VIEW_FUNC{
        usecase "Просмотр организацию\n в реестре" as viewOrg
        usecase "Сортировка" as sortOrg
        usecase "Фильтрация" as filterOrg
        usecase "Экспорт в Excel" as exportOrg
   }
}


rectangle "Акторы.Доступ: Введение" as CRUD_ACTORS {
    package "ОМСУ" as CRUD_OMSU {
         actor "Оператор ОМСУ" as opOMSU
    }
    package "ВетСлужба" as CRUD_VET {
        actor "Оператор ВетСлужбы" as opVet
    }
}

rectangle "Акторы.Доступ: Просмотр" as VIEW_ACTORS {
    package "ВетСлужба" as VIEW_VET {
        actor "Куратор ВетСлужбы" as curVet
        actor "Оператор ВетСлужбы" as opVet
        actor "Подписант ВетСлужбы" as podVet
    }

    package "Отлов" as Otlov{
    actor "Куратор по отлову" as curOtlov
    actor "Подписант по отлову" as podOtlov
    }

    package "Приют" as Pr{
    actor "Куратор приюта" as curPr
    actor "Подписант приюта" as podPr
    }

    package "ОМСУ" as OMSU {
    actor "Куратор ОМСУ" as curOMSU
    actor "Оператор ОМСУ" as opOMSU
    actor "Подписант ОМСУ" as podOMSU
    }
}
CRUD_ACTORS --> CRUD_FUNC
VIEW_ACTORS --> VIEW_FUNC


@enduml